### ISSUE TITLE
Use an environment variable to specify the ABE API URL

### ISSUE THREAD

**Issue by osteele** [olinlibrary/futureboard#298]
Change the ABE API URL from a constant to an environment variable. This will allow us to use configure different endpoints for development, staging, and production. (Also see [The Twelve-Factor App](https://12factor.net/config).)

Alternative approaches:
1. Add an API to the Futureboard server, that returns the ABE API server connection URL. The server reads this from `process.env.ABE_API_URL`. Con: This increases client initialization complexity (retrieving events has to be sequenced after receiving the URL; more failure modes).
2. Add an (e.g.) `config.js` *template* file, that contains `const ABE_API_URL = "https://abe.olin.build";` (where the server fills in the string value from the environment variable). HTML pages that include `board.html` or `events.html` include this file. Con: Adding this to just pages that include js that use the ABE API server is fragile.
3. Same as (2), but include `config.js` in all the pages. Con: even less DRY. There's already a lot of [WET](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself#DRY_vs_WET_solutions) boilerplate repeated across the HTML templates, though; maybe this doesn't significantly increase it.
4. Same as (2) or (3), but embed a `<script> const ABE_API_URL = …</script>` in each HTML template page. Con: this adds a dependency on a template engine (not currently used in the the project).
5. Modify the project to use webpack and [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/), to allow client js code to reference whitelisted `process.env[*]` variables. Pro: consistency with abe-web. Cons: this is a significant toolchain change, that I wouldn't want to make now or without Adam's involvement and approval.

**Comment by SeunginLyu** [comment]
:+1: I upvote option 5. Option 3 sounds good but the code is already WET enough :(

**Comment by osteele** [comment]
How about (2) now (since I already wrote it :-), and it solves the immediate problem), and a new issue for adding webpack?
